### ISSUE TITLE
Convert `db-users.txt` to a proper database

### ISSUE THREAD

**Issue by JDegner0129** [robhruska/CalendarToSlack#26]
The `db-users.txt` has outlived its usefulness. The more we add to this file, the harder it becomes to parse and to add extensions to. It'd be much easier to build on top of our existing data if it were stored in a format like a SQLite table that were easier to iterate on.

**Comment by robhruska** [comment]
This also gives us an opportunity to re-think whitelisting a bit more. Right now a whitelist entry needs to be set up for each mapping (e.g. "Working From Home" -> "WFH" and "Work From Home" -> "WFH"), mainly because it'd have been more complicated int he datastore. Reworking the DB may make this easier.

**Comment by robhruska** [comment]
Should also consider renaming "whitelisting" - that was the original intent, but now it's a combination of whitelisting and status mapping. Could come up with different semantics and terminology here.

**Comment by robhruska** [comment]
User
* Email
* SlackApplicationAuthToken

User Options/Preferences
* Enabled - whether or not the integration is enabled; currently only manually configurable, could add a slash command for this
* SlackbotNotify - whether or not to send slackbot messages for anything

User Whitelist/Statuses
* EventMatch - String match for calendar event. If matches, use the event name as custom status. Otherwise use a generic status like "Away" or "OOO"
* TranslateToStatus - May be null. If set and the EventMatch field matches the event, use this as the Slack status instead of the event name.
* Emoji - When matched, use this emoji.

**Comment by robhruska** [comment]
Alternative for User Whitelist/Status:

User Statuses
* Status
* Emoji

User Status Mappings (N;1 with user statuses)
* Match
* User Status Id

**Comment by JDegner0129** [comment]
Since the scope of this is larger than we thought, I'm going to close this issue -- I've made a [milestone](https://github.com/robhruska/CalendarToSlack/milestone/1) capturing it and will add smaller issues to it.
